<?php

namespace Database\Seeders;

use App\Models\MetaTag;
use Illuminate\Database\Seeder;

class MetaTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        MetaTag::truncate();
        $data = [
            [
                'page_name' => 'Home',
                'title' => 'Build consensus by canonizing what you believe is right',
                'is_static' => 1,
                'description' => 'Bringing the world together by canonizing what you believe is right. Your thoughts are processed through our pattented algorithims in a qualified & quantified camp where others can see, join & together change the world.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'BrowsePage',
                'title' => 'Browse Topics | Canonizer',
                'is_static' => 1,
                'description' => 'Your thoughts are processed through our pattented algorithims in a qualified & quantified camp where others can see, join & together change the world. Browse topics of interest.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'TopicDetailsPage',
                'title' => 'Canonizer',
                'is_static' => 0,
                'description' => '[Topic Description] limited to 160 characters.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'TopicHistoryPage',
                'title' => 'History | Canonizer',
                'is_static' => 0,
                'description' => '[Topic Description] limited to 160 characters.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampHistoryPage',
                'title' => 'History | Canonizer',
                'is_static' => 0,
                'description' => '[Camp Description] limited to 160 characters.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'StatementHistoryPage',
                'title' => 'Statement History | Canonizer',
                'is_static' => 0,
                'description' => 'Statement history feature provides an archive of all statements in a particular camp/topic.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CreateNewCampPage',
                'title' => 'Create New Camp | Canonizer',
                'is_static' => 1,
                'description' => 'Create a new single-level or multi-level camps under the parent camp to start Canonizing.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CreateNewStatement',
                'title' => 'Add Camp Statement | Canonizer',
                'is_static' => 1,
                'description' => 'Add a camp statement in an existing camp.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CreateNewTopicPage',
                'title' => 'Create New Topic | Canonizer',
                'is_static' => 1,
                'description' => 'Create and discuss on a new topic and bring the world together by canonizing what you believe is right.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'EditNewsPage',
                'title' => 'Update News | Canonizer',
                'is_static' => 1,
                'description' => 'Add a news link/video link limited to 2000 characters on any camp/topic of your choice.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumPage',
                'title' => 'Forum | Canonizer',
                'is_static' => 0,
                'description' => 'Post your ideas and reply to threads in our community-based support forums.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumListPage',
                'title' => 'Forum | Canonizer',
                'is_static' => 0,
                'description' => 'Post your ideas and reply to threads in our community-based support forums.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumCreatePage',
                'title' => 'Create New Thread | Canonizer',
                'is_static' => 1,
                'description' => 'Create a new thread in the existing camp with your title and name.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumEditPage',
                'title' => 'Update Thread | Canonizer',
                'is_static' => 1,
                'description' => 'Edit the existing thread in the forum where people discuss and share their opinions.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'LoginPage',
                'title' => 'Login and Start Canonizing | Canonizer',
                'is_static' => 1,
                'description' => 'Log in to Canonizer to start canonizing what you believe is right.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageCampPage',
                'title' => 'Update Camp | Canonizer',
                'is_static' => 1,
                'description' => 'Briefly describe your changes and update all the camp summary under the existing camp.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageStatementPage',
                'title' => 'Manage Statement | Canonizer',
                'is_static' => 1,
                'description' => 'Update your statement under the existing camp. Briefly describe your changes with wiki markup.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CompareStatementPage',
                'title' => 'Compare Statements | Canonizer',
                'is_static' => 1,
                'description' => 'Check out different statements and compare them with other statements in terms of topic summary, live time, and different other aspects.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageSupport',
                'title' => 'Manage Supported Camps | Canonizer',
                'is_static' => 1,
                'description' => 'Check all the Supported Camps under an existing topic. You can also support different camps as and when required.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'Support',
                'title' => 'Manage Supported Camps | Canonizer',
                'is_static' => 1,
                'description' => 'Check all the Supported Camps under an existing topic. You can also support different camps as and when required.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'VideosPage',
                'title' => 'Videos | Canonizer',
                'is_static' => 1,
                'description' => 'Watch and understand each aspect of consciousness, as it is said that consciousness is not a hard problem, but rather a colour problem.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'RecentActivitiesPage',
                'title' => 'Recent User Activities | Canonizer',
                'is_static' => 1,
                'description' => 'View all the activities you\'ve done recently, such as creating topics & threads and response on various topics.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ForgotPasswordPage',
                'title' => 'Forgot Password | Canonizer',
                'is_static' => 1,
                'description' => 'Forgot your password? Please enter your email address so we can send you an email to reset your password.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'NotificationsListPage',
                'title' => 'Notifications | Canonizer',
                'is_static' => 1,
                'description' => 'List of all notifications.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'PrivacyPolicy',
                'title' => 'Privacy Policy | Canonizer',
                'is_static' => 1,
                'description' => 'Bringing the world together by canonizing what you believe is right. Your thoughts are processed through our pattented algorithims in a qualified & quantified camp where others can see, join & together change the world.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'RegistrationPage',
                'title' => 'Register and Start Canonizing | Canonizer',
                'is_static' => 1,
                'description' => 'Create an account on Canonizer to start canonizing what you believe is right.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'Settings',
                'title' => 'Settings | Canonizer',
                'is_static' => 1,
                'description' => 'Update your profile info, change password, and view your supported camps under one roof.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'TermAndService',
                'title' => 'Terms and Service | Canonizer',
                'is_static' => 1,
                'description' => 'Bringing the world together by canonizing what you believe is right. Your thoughts are processed through our pattented algorithims in a qualified & quantified camp where others can see, join & together change the world.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'UploadFile',
                'title' => 'Upload File | Canonizer',
                'is_static' => 1,
                'description' => 'Upload files that you want to use in a topic or camp.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'UserProfile',
                'title' => 'User Profile | Canonizer',
                'is_static' => 1,
                'description' => 'View user\'s details like name, email, and date of birth, along with a list of supported camps.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageTopicPage',
                'title' => 'Update Topic | Canonizer',
                'is_static' => 1,
                'description' => 'Update your existing topic and briefly describe your changes before submitting.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'AddNewsPage',
                'title' => 'Add News | Canonizer',
                'is_static' => 1,
                'description' => 'Add or create news in a camp or topic.',
                'submitter_nick_id' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
    
        foreach ($data as $value) {
            MetaTag::create($value);
        }
    }
}
