<?php

namespace Database\Seeders;

use App\Models\MetaTag;
use Illuminate\Database\Seeder;

class MetaTagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        MetaTag::truncate();
        $data = [
            [
                'page_name' => 'Home',
                'title' => 'Canonizer | Changing the World together',
                'is_static' => 1,
                'description' => 'Bringing the world together by canonizing what you believe is right.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => ['canonizer', 'home-page'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'BrowsePage',
                'title' => 'Canonizer | View all topics',
                'is_static' => 1,
                'description' => 'Browse all topics in all namespaces, alphabetically.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => ['canonizer', 'about_us', 'about-us'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'TopicDetailsPage',
                'title' => 'Canonizer | Topics | Topic Details',
                'is_static' => 0,
                'description' => 'Open survey system designed to register and quantify the contemporary consensus on contentious issues that are in a state of flux.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'TopicHistoryPage',
                'title' => 'Canonizer | Topics | Topic History',
                'is_static' => 0,
                'description' => 'Collaboratively generate concise statements describing the various "camps" on this issue to come up with a quantitative measure/solution.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampHistoryPage',
                'title' => 'Canonizer | Camp | Camp Development',
                'is_static' => 0,
                'description' => 'A wiki based system that eliminates edit wars by giving users the ability to create, join, and develop camps.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'StatementHistoryPage',
                'title' => 'Canonizer | View History',
                'is_static' => 0,
                'description' => 'Add a camp statement, manage and edit topic history, and view and edit camp history, all from one place.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CreateNewCampPage',
                'title' => 'Canonizer | Camp | Camp Structure',
                'is_static' => 1,
                'description' => 'Canonizer.com\'s camp structure encourages people to find the most important issues to emphasize.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CreateNewStatement',
                'title' => 'Canonizer | Camp | Camp Statement',
                'is_static' => 1,
                'description' => 'Canonizer.com\'s camp statement provides ways to collect concise and quantitative input from all points of view.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CreateNewTopicPage',
                'title' => 'Canonizer | Topic | Topic Creation',
                'is_static' => 1,
                'description' => 'Discuss a topic that emphasises on the important issue over the minor one.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'EditNewsPage',
                'title' => 'Canonizer | News | Edit News',
                'is_static' => 1,
                'description' => 'Add a news link/video link limited to 2000 characters on any camp/topic of your choice.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumPage',
                'title' => 'Canonizer | Forum | Topics',
                'is_static' => 0,
                'description' => 'Post your ideas and reply to threads in our community-based support forums.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumPostPage',
                'title' => 'Canonizer | Forum | Post | Topics',
                'is_static' => 0,
                'description' => 'Post your ideas and reply to threads in our community-based support forums.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumCreatePage',
                'title' => 'Canonizer | Forum | Forum Creation',
                'is_static' => 1,
                'description' => 'Create forums by giving your views to any camp statement and viewing all the threads in that forum.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CampForumEditPage',
                'title' => 'Canonizer | Forum | Edit Forum',
                'is_static' => 1,
                'description' => 'Each camp has a discussion forum where people can share their opinions, you can edit or create new threads on the topics required.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'LoginPage',
                'title' => 'Canonizer | User Login',
                'is_static' => 1,
                'description' => 'Log in to Canonizer with your details. Enter your emai, password or request for an OTP.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageCampPage',
                'title' => 'Canonizer | Camp | Camp Management',
                'is_static' => 1,
                'description' => 'Manage all the camps, change, or edit the camp from a single place.The camp-tree structure encourages as much consensus as possible on any theoretical topic.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageStatementPage',
                'title' => 'Canonizer | Statement | Manage',
                'is_static' => 1,
                'description' => 'Manage all of the camp statements in one place. Know whether your query is active, under review, or has an old status.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageHistory',
                'title' => 'Canonizer | History | Manage',
                'is_static' => 1,
                'description' => 'Check the camp statement history and update the statement with your name, statement, and summary.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'CompareStatementPage',
                'title' => 'Canonizer | Statement Comparision',
                'is_static' => 1,
                'description' => 'Check out different topics and compare them in terms of topic summary, live time, and different other aspects.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ManageSupport',
                'title' => 'Canonizer | Support | Manage',
                'is_static' => 1,
                'description' => 'Directly join and support any topic on any camp, all in one place.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'Support',
                'title' => 'Canonizer | Support | User',
                'is_static' => 1,
                'description' => 'Get all the details of the user and the list of supported camps in one place.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'VideosPage',
                'title' => 'Canonizer | Videos | Conciousness',
                'is_static' => 1,
                'description' => 'Watch and understand each aspect of consciousness knowledge, as it is said that consciousness is not a difficult problem, but rather a colour problem.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'RecentActivitiesPage',
                'title' => 'Canonizer | Activites',
                'is_static' => 1,
                'description' => 'Know all the activities you\'ve done recently, such as creating topics, responding to various topics, and so on.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'ForgotPasswordPage',
                'title' => 'Canonizer | Sign Up | Forgot Password',
                'is_static' => 1,
                'description' => 'Forgot your password? Please enter your email address so we can send you an email to reset your password.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'NotificationsListPage',
                'title' => 'Canonizer | Notification',
                'is_static' => 1,
                'description' => 'Get a message or notification whenever any user adds their point of view to your selected camp.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'PrivacyPolicy',
                'title' => 'Canonizer | Privacy - Policy',
                'is_static' => 1,
                'description' => 'The Privacy Policy page will let you know what information we collect, why we collect it, and how you can update, manage, and delete your data.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'RegistrationPage',
                'title' => 'Canonizer | Sign up | Registration',
                'is_static' => 1,
                'description' => 'Register or sign up using your email address, mobile number, or social media accounts. Google+ Facebook Twitter GitHub Linkedin.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'Settings',
                'title' => 'Canonizer | Settings',
                'is_static' => 1,
                'description' => 'Update your profile info, change passwords, and view your supported camps all under one roof.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'TermAndService',
                'title' => 'Canonizer | Terms-And-Services',
                'is_static' => 1,
                'description' => 'Understand all terms and services. No person can have more than one identity. Human Identity: Bots are not permitted on Canonizer.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'UploadFile',
                'title' => 'Canonizer | File Upload',
                'is_static' => 1,
                'description' => 'Upload your files with the file name (maximum 5 MB). Once a file is uploaded, there is no way to delete it.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'UserProfile',
                'title' => 'Canonizer | User',
                'is_static' => 1,
                'description' => 'Get all the details of the user, like name, email, and date of birth, along with a list of supported camps.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'page_name' => 'Default',
                'title' => 'Canonizer | Default',
                'is_static' => 1,
                'description' => 'Filter your requirements based on your needs or get topics by default.',
                'submitter_nick_id' => null,
                'image_url' => 'https://canonizer3.canonizer.com/color-problem.png',
                'keywords' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
    
        foreach ($data as $value) {
            MetaTag::create($value);
        }
    }
}
